# Generated by Django 5.1 on 2025-01-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRole', '0002_alter_userdetail_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='device_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
