from django.contrib import admin
from .models import *

# Register your models here.
admin.site.register(PADeathReport)
admin.site.register(TTDReport)
admin.site.register(PermanentPartialDisabilityFinalClosureReport)
admin.site.register(PersonalAccidentHDCFinalClosureReport)
admin.site.register(LossOfJobFinalClosureReport)
admin.site.register(SecureMindCriticalIllnessFinalReport)
admin.site.register(SecureMindCriticalIllnessDeathFinalReport)
admin.site.register(SecureMindCriticalIllnessLiveFinalReport)
admin.site.register(GroupCashlessClosureReport)
admin.site.register(GroupReimbursementFinalClosureReport)
admin.site.register(PermanentTotalDisabilityFinalClosureReport)
admin.site.register(RetailCashlessFinalReport)
admin.site.register(RetailReimbursementFinalReport)
admin.site.register(SecureMindClaimHospitalDailyCashFinalClosureReport)
admin.site.register(SpecificVectorBornDiseaceReport)
admin.site.register(TravelFinalClosureReport)
admin.site.register(WorkmanCompensationFinalClosureReport)
admin.site.register(BrokenBones)
admin.site.register(HospitalDailyCashFinalClosureReport)
admin.site.register(LicClaimInvestigationReport)
admin.site.register(NationlInvestigationReport)
admin.site.register(NewIndiaInvestigationReport)
admin.site.register(OrientalFormatInvestigationReport)
admin.site.register(UnitedIndiaInvestigationReport)
admin.site.register(OtherInsuranceInvestigationReport)
