# Generated by Django 5.1 on 2025-02-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='visit_type',
            field=models.CharField(choices=[('hospital', 'hospital'), ('lab', 'lab'), ('chemist', 'chemist')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
