# Generated by Django 5.1 on 2025-02-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0002_question_visit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='visit_type',
            field=models.CharField(choices=[('hospital', 'hospital'), ('lab', 'lab'), ('chemist', 'chemist'), ('insured', 'insured')], max_length=20),
        ),
    ]
