# Generated by Django 5.1 on 2024-11-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.IntegerField()),
                ('hod_id', models.CharField(max_length=100)),
                ('coordinator_id', models.CharField(max_length=100)),
                ('medical_officer_id', models.CharField(max_length=100)),
                ('data_entry_id', models.CharField(max_length=100)),
                ('document_paths', models.JSONField()),
                ('case_status', models.CharField(choices=[('Creation', 'Creation'), ('Creation_confirmation', 'Creation Confirmation'), ('Investigation', 'Investigation'), ('Investigation_confirmation', 'Investigation Confirmation'), ('Medical', 'Medical'), ('Medical_confirmation', 'Medical Confirmation'), ('Data_entry', 'Data Entry'), ('Data_entry_confirmation', 'Data Entry Confirmation'), ('Final_report', 'Final Report'), ('Final_report_confirmation', 'Final Report Confirmation'), ('Complete', 'Complete')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CaseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.IntegerField()),
                ('coordinator_id', models.CharField(max_length=100)),
                ('claim_number', models.CharField(max_length=100)),
                ('insurance_company', models.CharField(max_length=255)),
                ('type_of_case', models.CharField(max_length=255)),
                ('rate', models.CharField(max_length=255)),
                ('medical_officer_remarks', models.TextField()),
                ('status_of_claim', models.CharField(choices=[('Pass', 'Pass'), ('Reject', 'Reject')], max_length=50)),
                ('claim_approved_amount', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FinalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.IntegerField()),
                ('insured_name', models.CharField(max_length=255)),
                ('hospital_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('RC', models.CharField(max_length=255)),
                ('RR', models.CharField(max_length=255)),
                ('GC', models.CharField(max_length=255)),
                ('GR', models.CharField(max_length=255)),
                ('PA_Death', models.CharField(max_length=255)),
                ('IPA', models.CharField(max_length=255)),
                ('GPA', models.CharField(max_length=255)),
                ('SMC_PA', models.CharField(max_length=255)),
                ('HDC', models.CharField(max_length=255)),
                ('LOJ', models.CharField(max_length=255)),
                ('WC', models.CharField(max_length=255)),
                ('PTD', models.CharField(max_length=255)),
                ('TTD', models.CharField(max_length=255)),
                ('SMC', models.CharField(max_length=255)),
                ('PPD', models.CharField(max_length=255)),
            ],
        ),
    ]
