# Generated by Django 5.1.3 on 2024-11-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0002_alter_case_data_entry_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_status',
            field=models.CharField(choices=[('Creation', 'Creation'), ('Creation_confirmation', 'Creation Confirmation'), ('Investigation', 'Investigation'), ('Investigation_confirmation', 'Investigation Confirmation'), ('Medical', 'Medical'), ('Medical_confirmation', 'Medical Confirmation'), ('Data_entry', 'Data Entry'), ('Data_entry_confirmation', 'Data Entry Confirmation'), ('Final_report', 'Final Report'), ('Final_report_confirmation', 'Final Report Confirmation'), ('Complete', 'Complete')], default='Creation', max_length=50),
        ),
    ]
