# Generated by Django 5.1 on 2024-12-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0003_alter_case_case_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedetails',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='casedetails',
            name='claim_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='casedetails',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='casedetails',
            name='doa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='casedetails',
            name='dod',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='casedetails',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='casedetails',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
