# Generated by Django 5.1 on 2025-01-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0005_casedetails_final_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='claim_number',
            field=models.CharField(default='', max_length=100),
        ),
    ]
