# Generated by Django 5.1 on 2025-01-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0006_case_claim_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancecompany',
            name='GC',
        ),
        migrations.RemoveField(
            model_name='insurancecompany',
            name='GPA',
        ),
        migrations.RemoveField(
            model_name='insurancecompany',
            name='GR',
        ),
        migrations.RemoveField(
            model_name='insurancecompany',
            name='IPA',
        ),
        migrations.RemoveField(
            model_name='insurancecompany',
            name='RC',
        ),
        migrations.RemoveField(
            model_name='insurancecompany',
            name='RR',
        ),
        migrations.RemoveField(
            model_name='insurancecompany',
            name='SMC',
        ),
        migrations.RemoveField(
            model_name='insurancecompany',
            name='SMC_PA',
        ),
        migrations.AddField(
            model_name='insurancecompany',
            name='Broken_Bones',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insurancecompany',
            name='Group',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insurancecompany',
            name='PA_HDC',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insurancecompany',
            name='Retail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insurancecompany',
            name='SMC_CI_Death_Live',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insurancecompany',
            name='SMC_HDC',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='insurancecompany',
            name='HDC',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='insurancecompany',
            name='LOJ',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='insurancecompany',
            name='PA_Death',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='insurancecompany',
            name='PPD',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='insurancecompany',
            name='PTD',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='insurancecompany',
            name='TTD',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='insurancecompany',
            name='WC',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
