# Generated by Django 5.1 on 2024-11-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_id', models.IntegerField()),
                ('doa', models.DateTimeField()),
                ('dod', models.DateTimeField()),
                ('hospital_name', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('claim_value', models.CharField(max_length=100)),
                ('diagnosis', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=100)),
                ('no_of_beds', models.IntegerField()),
                ('icu', models.BooleanField()),
                ('ot', models.BooleanField()),
                ('nursing_staff', models.IntegerField()),
                ('rmo', models.IntegerField()),
                ('td_registration_number', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('owner_of_the_hospital', models.CharField(max_length=255)),
                ('doctor_registration_number', models.CharField(max_length=100)),
                ('doctor_contact_number', models.CharField(max_length=15)),
                ('doctor_email', models.EmailField(max_length=254)),
                ('questions', models.JSONField()),
                ('document_paths', models.JSONField()),
                ('photo_path', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='LabVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('pathologist_name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=100)),
                ('questions', models.JSONField()),
                ('document_paths', models.JSONField()),
                ('photo_path', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_id', models.IntegerField()),
                ('name_of_chemist', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=255)),
                ('gst_number', models.CharField(max_length=100)),
                ('drug_license_number', models.CharField(max_length=100)),
                ('questions', models.JSONField()),
                ('document_paths', models.JSONField()),
                ('photo_path', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_id', models.IntegerField()),
                ('case_id', models.IntegerField()),
                ('coordinator_id', models.CharField(max_length=100)),
                ('investigator_id', models.CharField(max_length=100)),
                ('type_of_visit', models.CharField(choices=[('Hospital', 'Hospital'), ('Treating_doctor', 'Treating Doctor'), ('Lab', 'Lab'), ('Chemist', 'Chemist')], max_length=50)),
                ('tat', models.CharField(max_length=100)),
                ('visit_status', models.CharField(choices=[('Investigation', 'Investigation'), ('Investigation_confirmation', 'Investigation Confirmation')], max_length=50)),
            ],
        ),
    ]
