# Generated by Django 5.1 on 2024-12-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalvisit',
            name='document_paths',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalvisit',
            name='photo_path',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalvisit',
            name='questions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labvisit',
            name='document_paths',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labvisit',
            name='photo_path',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labvisit',
            name='questions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacyvisit',
            name='document_paths',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacyvisit',
            name='photo_path',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacyvisit',
            name='questions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
