# Generated by Django 5.1 on 2024-12-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visit', '0002_alter_hospitalvisit_document_paths_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalvisit',
            name='doa',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hospitalvisit',
            name='doctor_email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hospitalvisit',
            name='dod',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hospitalvisit',
            name='icu',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hospitalvisit',
            name='no_of_beds',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hospitalvisit',
            name='nursing_staff',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hospitalvisit',
            name='ot',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hospitalvisit',
            name='rmo',
            field=models.CharField(max_length=255),
        ),
    ]
