# Generated by Django 5.1 on 2024-12-25 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visit', '0004_hospitalvisit_answers_labvisit_answers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyvisit',
            name='state',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
