# Generated by Django 5.1 on 2024-12-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visit', '0005_pharmacyvisit_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='investigation_started',
            field=models.BooleanField(default=False),
        ),
    ]
