# Generated by Django 5.1 on 2024-12-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visit', '0006_visit_investigation_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='issue_in_investigation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visit',
            name='issue_of_investigator',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
