# Generated by Django 5.1 on 2024-12-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visit', '0007_visit_issue_in_investigation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='submitted_by_investigator',
            field=models.BooleanField(default=False),
        ),
    ]
