# Generated by Django 5.1 on 2024-12-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visit', '0008_visit_submitted_by_investigator'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='re_investigation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visit',
            name='re_investigation_reason',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
