# Generated by Django 5.1 on 2025-01-22 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Visit', '0009_visit_re_investigation_visit_re_investigation_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitalvisit',
            old_name='td_registration_number',
            new_name='treating_doctor_registration_number',
        ),
    ]
