# Generated by Django 5.1 on 2025-01-22 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Visit', '0010_rename_td_registration_number_hospitalvisit_treating_doctor_registration_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitalvisit',
            old_name='degree',
            new_name='treating_doctor_degree',
        ),
        migrations.RemoveField(
            model_name='hospitalvisit',
            name='doctor_registration_number',
        ),
    ]
