# Generated by Django 5.1 on 2025-01-22 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Visit', '0011_rename_degree_hospitalvisit_treating_doctor_degree_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitalvisit',
            old_name='doctor_contact_number',
            new_name='treating_doctor_contact_number',
        ),
        migrations.RenameField(
            model_name='hospitalvisit',
            old_name='doctor_email',
            new_name='treating_doctor_email',
        ),
    ]
