# Generated by Django 5.1 on 2025-01-23 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visit', '0012_rename_doctor_contact_number_hospitalvisit_treating_doctor_contact_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitalvisit',
            old_name='owner_of_the_hospital',
            new_name='name_of_hospital_owner',
        ),
        migrations.AddField(
            model_name='hospitalvisit',
            name='hospital_owner_contact_number',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospitalvisit',
            name='hospital_owner_registration_number',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
