# Generated by Django 5.1 on 2025-01-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visit', '0013_rename_owner_of_the_hospital_hospitalvisit_name_of_hospital_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitalvisit',
            old_name='name_of_hospital_owner',
            new_name='hospital_owner_name',
        ),
        migrations.AddField(
            model_name='hospitalvisit',
            name='anaesthetic_doctor_contact_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospitalvisit',
            name='anaesthetic_doctor_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospitalvisit',
            name='anaesthetic_doctor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospitalvisit',
            name='anaesthetic_doctor_registration_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospitalvisit',
            name='family_physician_contact_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospitalvisit',
            name='family_physician_doctor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospitalvisit',
            name='family_physician_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospitalvisit',
            name='family_physician_registration_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
