# Generated by Django 5.1 on 2025-01-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visit', '0014_rename_name_of_hospital_owner_hospitalvisit_hospital_owner_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalvisit',
            name='corporate_visit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hospitalvisit',
            name='work_place',
            field=models.BooleanField(default=False),
        ),
    ]
