# Generated by Django 5.1 on 2025-02-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visit', '0015_hospitalvisit_corporate_visit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='hospitalvisit',
            name='treating_doctor_contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalvisit',
            name='treating_doctor_degree',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalvisit',
            name='treating_doctor_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalvisit',
            name='treating_doctor_registration_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
