# Generated by Django 5.1 on 2025-02-02 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Visit', '0016_cityvisit_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CityVisit',
            new_name='City',
        ),
    ]
