# Generated by Django 5.1 on 2025-02-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visit', '0017_rename_cityvisit_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='visit_completed',
            field=models.BooleanField(default=False),
        ),
    ]
