# Generated by Django 5.1 on 2025-02-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visit', '0018_visit_visit_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuredVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_id', models.IntegerField()),
                ('insured_name', models.CharField(max_length=255)),
                ('insured_age', models.CharField(max_length=10)),
                ('insured_contact_number', models.CharField(max_length=15)),
                ('insured_address', models.TextField()),
                ('insured_city', models.CharField(max_length=255)),
                ('insured_state', models.CharField(max_length=255)),
                ('questions', models.JSONField(blank=True, null=True)),
                ('answers', models.JSONField(blank=True, null=True)),
                ('document_paths', models.JSONField(blank=True, null=True)),
                ('photo_path', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
