# Generated by Django 5.1 on 2025-02-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visit', '0021_rename_insured_address_insuredvisit_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='visit_cost',
            field=models.CharField(default='', max_length=50),
        ),
    ]
